### ISSUE TITLE
Required updates for ipywidgets 8.0 

### ISSUE THREAD

**Issue by philippjfr** [bokeh/ipywidgets_bokeh#10]
In ipywidgets 8.0 (not yet released) the `WidgetManager.display_model` method will be deleted as can be seen here: https://github.com/jupyter-widgets/ipywidgets/pull/2752. This will require some updates to `ipywidgets_bokeh`.

**Comment by fleming79** [comment]
Ipywidgets now has a beta version here: https://github.com/jupyter-widgets/ipywidgets/pull/3332. It would be great if a compatible version of ipywidets_bokeh is made available.
