### ISSUE TITLE
Ipywidgets not getting rendered in Panel accordion

### ISSUE THREAD

**Issue by aditya3434** [bokeh/ipywidgets_bokeh#102]
Ipywidgets don't get rendered when using inside a Panel accordion.

Panel version : 1.2.4
Bokeh version : 3.3.0

Reproducer :
```
import panel as pn
import ipywidgets as ipw
pn.extension()
basic_view_btn = ipw.Button(description="Click me")
accordion = pn.Accordion(
    ('Button', pn.Row(basic_view_btn)),
    ('Panel Button', pn.Row(pn.widgets.Button(name='hello')))
)
accordion.servable()
```

Output :
<img width="146" alt="image" src="https://github.com/bokeh/ipywidgets_bokeh/assets/56246494/c822f859-92f6-4ec8-aa5c-a5e751e14705">

Console Error :
<img width="357" alt="image" src="https://github.com/bokeh/ipywidgets_bokeh/assets/56246494/450e9585-b667-440a-90cd-7d131061a4ae">

**Comment by ndmlny-qs** [comment]
@aditya3434 can you confirm the version of Panel you are using? I do not see a release on pypi that is 1.2.4 https://pypi.org/project/panel/#history, and the 1.2.3 release pins Bokeh to be less than 3.3.

**Comment by singharpit94** [comment]
The  issue still happens with panel 1.3.0 and bokeh 3.3.0 @ndmlny-qs .Let me know if you are not able to reproduce it with the mentioned versions.

**Comment by philippjfr** [comment]
This is really Panel's fault I think, I'll push a fix.
