### ISSUE TITLE
UI cluttered while tring to use this library

### ISSUE THREAD

**Issue by ItamarShDev** [bokeh/ipywidgets_bokeh#18]
Using the following code:
```python
import panel as pn
from ipywidgets_bokeh import IPyWidget
from ipywidgets import FloatSlider
pn.extension()
angle = FloatSlider(min=0, max=360, value=0, step=1, description="Angle")
wrapper = IPyWidget(widget=angle, width=800, height=800)
pn.Row(wrapper)
```

resolved most times in the following UI clutter:
![image](https://user-images.githubusercontent.com/953371/95046664-4637a600-06ed-11eb-9961-33c5ccc2bae5.png)

**Comment by ItamarShDev** [comment]
versions
![image](https://user-images.githubusercontent.com/953371/95047030-fc02f480-06ed-11eb-8a92-69e7205f018d.png)

**Comment by birdsarah** [comment]
I'm confused. What's hapepning here @ItamarShDev? It looks like your first picture just didn't finish loading.

**Comment by ItamarShDev** [comment]
The image is loaded fine. 
What happens is:
Once I run the cell, the whole hi disappear.
Inspecting it shows that some div shrinks to around 80px and everything is hidden below it.

**Comment by philippjfr** [comment]
This library should **not** be used in a Jupyter context it's only for server deployment. In Panel you can instead just use the IPyWidget directly:

```python
import panel as pn
from ipywidgets import FloatSlider

pn.extension()

angle = FloatSlider(min=0, max=360, value=0, step=1, description="Angle")
pn.Row(angle)
```
