### ISSUE TITLE
ipywidgets_bokeh does not understand how to include/ handle the LayerGroup ipywidgets child model from ipyleaflet

### ISSUE THREAD

**Issue by joel314** [bokeh/ipywidgets_bokeh#34]
Hi,

I am using Panel to display a map with LayerGroup, using ipyleaflet. The grouped layers are not rendered on the map.

This problem is described with great details on this [link](https://github.com/holoviz/panel/issues/2710).

I am opening an issue on ipywidgets_bokeh because @philippjfr commented [here](https://github.com/holoviz/panel/issues/2710#issuecomment-913130481) that the issue was related to this project.

Thanks for your help.

**Comment by MarcSkovMadsen** [comment]
Listening in. I am also interested in a solution to this.

**Comment by philippjfr** [comment]
This is a bug in ipyleaflet:

https://github.com/jupyter-widgets/ipyleaflet/blob/master/js/src/layers/LayerGroup.js#L11

The LayerGroup class does not inherit the attributes from the parent so ipywidgets_bokeh cannot resolve the module and version of the model.

**Comment by philippjfr** [comment]
Fixed in https://github.com/jupyter-widgets/ipyleaflet/pull/873

**Comment by philippjfr** [comment]
Closing since this is not an ipywidgets_bokeh bug.

**Comment by joel314** [comment]
Thank you @philippjfr and @MarcSkovMadsen
