### ISSUE TITLE
ipysheet

### ISSUE THREAD

**Issue by riziles** [bokeh/ipywidgets_bokeh#54]
Quick question: I'm trying to use the [ipysheet](https://github.com/QuantStack/ipysheet) widget in Panel, but it's not working. The issue *seems* to be that the [require_loader](https://github.com/bokeh/ipywidgets_bokeh/blob/main/ipywidgets_bokeh/src/loader.ts) function is generating a CDN path for https://unpkg.com/ipysheet@0.5.0/dist/index.js , but the file is at https://unpkg.com/ipysheet@0.5.0/lib/index.js . I can't see any way around it because the "dist" is hard coded. Any suggestions as to how to resolve this incompatibility?

**Comment by ndmlny-qs** [comment]
@riziles did the fix discussed here https://github.com/QuantStack/ipysheet/issues/230 solve the issue you described?

**Comment by riziles** [comment]
> @riziles did the fix discussed here [QuantStack/ipysheet#230](https://github.com/QuantStack/ipysheet/issues/230) solve the issue you described?

Yes! See discussion here: https://discourse.holoviz.org/t/ipysheet-an-ipywidget-based-spreadsheet-that-works-with-panel/2685/11?u=riziles

**Comment by ndmlny-qs** [comment]
Great, then I'll close the issue. Thanks very much for the link to the discourse discussion.
