### ISSUE TITLE
Not working with anywidget:  Class null not found in module @jupyter-widgets/base@2.0.0

### ISSUE THREAD

**Issue by MarcSkovMadsen** [bokeh/ipywidgets_bokeh#89]
[anywidget](https://[anywidget](https://anywidget.dev/).dev/) is a new way of developing ipywidgets with a claim for being easier and more modern. For example [mapwidget](https://github.com/giswqs/mapwidget) is built on top of anywidget.

I reported in https://github.com/bokeh/ipywidgets_bokeh/issues/88 that mapwidget.cesium is not working with ipywidgets-bokeh and Panel. So I thought I would try out a basic anywidget example. And I can see that it raises the same issue.

## Reproducible Example

```bash
pip install panel==0.14.4 ipywidgets-bokeh==1.3.0 anywidget==0.2.0
```

**script.py**

```python
import anywidget
import traitlets

import panel as pn

pn.extension("ipywidgets")

class CounterWidget(anywidget.AnyWidget):
    _esm = """
    export function render(view) {
      let getCount = () => view.model.get("count");
      let button = document.createElement("button");
      button.classList.add("counter-button");
      button.innerHTML = `count is ${getCount()}`;
      button.addEventListener("click", () => {
        view.model.set("count", getCount() + 1);
        view.model.save_changes();
      });
      view.model.on("change:count", () => {
        button.innerHTML = `count is ${getCount()}`;
      });
      view.el.appendChild(button);
    }
    """
    _css="""
    .counter-button { background-color: #ea580c; }
    .counter-button:hover { background-color: #9a3412; }
    """
    count = traitlets.Int(0).tag(sync=True)

counter = CounterWidget()
pn.panel(counter).servable()
```

```bash
panel serve script.py
```

Open http://localhost:5006/script and see the exception in the browser console.

![image](https://user-images.githubusercontent.com/42288570/227778927-9e0dace3-0cab-4ff5-97a1-649c71bc85f0.png)

```bash
Class null not found in module @jupyter-widgets/base@2.0.0
```

**Comment by ndmlny-qs** [comment]
@MarcSkovMadsen I can get your example to run in Jupyter, but I do get the same error you mention when running `panel serve ...`.

[ipy-bk-issue89.webm](https://user-images.githubusercontent.com/60523020/227972124-6507466e-10df-4d6a-af15-592fbc17397f.webm)

I'll investigate more and see what I can find.

**Comment by MarcSkovMadsen** [comment]
Works with Solara. See https://twitter.com/maartenbreddels/status/1662550931047604225?s=46&t=QCeLnYcdhHHHwawHQ7y8xA

**Comment by MarcSkovMadsen** [comment]
I can confirm Anywidget now works with Panel. See https://discourse.holoviz.org/t/panel-works-with-anywidget/6466
